name: Deploy Frontend & Backend Split Mode

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev

    ### FRONTEND (SSR UI on VPC Public) ###
    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend:${{ github.sha }} .

    - name: Push frontend image
      run: |
        docker push ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend:${{ github.sha }}

    - name: Deploy frontend
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: frontend
        image: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend:${{ github.sha }}
        region: asia-southeast2
        allow_unauthenticated: true
        vpc_connector: vpc-public
        env_vars: |
          MODE=FRONTEND
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DATABASE_URL_WITH_SCHEMA=${{ secrets.DATABASE_URL_WITH_SCHEMA }}
          FRONTEND_URL=https://codeleap.sunaryathito.space
          BACKEND_URL=https://backendcodeleap.sunaryathito.space
          BUCKET_SERTIFIKAT=codeleap-sertifikat
          BUCKET_MATERI=codeleap-materi

    ### BACKEND (API on VPC Private) ###
    - name: Build backend image
      run: |
        docker build -t ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/backend:${{ github.sha }} .

    - name: Push backend image
      run: |
        docker push ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/backend:${{ github.sha }} .

    - name: Deploy backend
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: backend
        image: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/backend:${{ github.sha }}
        region: ${{ secrets.GCP_LOCATION }}
        allow_unauthenticated: false
        ingress: internal
        vpc_connector: vpc-private
        env_vars: |
          MODE=BACKEND
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DATABASE_URL_WITH_SCHEMA=${{ secrets.DATABASE_URL_WITH_SCHEMA }}
          FRONTEND_URL=https://codeleap.sunaryathito.space
          BACKEND_URL=https://backendcodeleap.sunaryathito.space
          BUCKET_SERTIFIKAT=codeleap-sertifikat
          BUCKET_MATERI=codeleap-materi
