name: Deploy Next.js to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for GAR
      run: gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE_URI="${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-images/codeleap:latest"
        docker build -t "$IMAGE_URI" .
        docker push "$IMAGE_URI"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy codeleap  \
          --image "${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-images/codeleap:latest" \
          --platform managed \
          --region ${{ secrets.GCP_LOCATION }} \
          --port 3000 \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 1 \
          --project ${{ secrets.GCP_PROJECT_ID  }} \
          --service-account ${{ secrets.GCP_PROJECT_SA_NAME }} \
