name: Deploy Next.js to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nextjs-repo/codeleap-app:$GITHUB_SHA .

    - name: Push to Artifact Registry
      run: |
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nextjs-repo/codeleap-app:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy codeleap-app \
          --image asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nextjs-repo/codeleap-app:$GITHUB_SHA \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
